### ISSUE TITLE
Explain the relation to String.prototype.localeCompare, if any

### ISSUE THREAD

**Issue by domenic** [littledan/toCaseFold#2]
My understanding is there is no relation because localeCompare is meant to be case-sensitive. We may want to add some sort of case-insensitive localeCompare (either as an option or a separate method), but toCaseFold is the primitive building block and per #1 is a better one to expose first.

**Comment by littledan** [comment]
I think case-insensitive localeCompare would be a good idea to put as part of a collation key API--you'd get the collation key slicing off the final priority aspect, the case.  I'll try to explain the relationship in the explainer.

**Comment by littledan** [comment]
Fixed in https://github.com/littledan/toCaseFold/commit/7b588b37803790072f7610605ea13c6be3d7baed
